/*
Author: Amit Gupta
Date: 09-08-2026
*/

#include <iostream>
using namespace std;

int main() {
    int num;
    cout << "Enter an integer between 1 and 100:- ";
    cin >> num;

    if (num == 1) {
        cout << "You entered 1" << endl;
    } else if (num == 2) {
        cout << "You entered 2" << endl;
    } else if (num == 3) {
        cout << "You entered 3" << endl;
    } else if (num == 4) {
        cout << "You entered 4" << endl;
    } else if (num == 5) {
        cout << "You entered 5" << endl;
    } else if (num == 6) {
        cout << "You entered 6" << endl;
    } else if (num == 7) {
        cout << "You entered 7" << endl;
    } else if (num == 8) {
        cout << "You entered 8" << endl;
    } else if (num == 9) {
        cout << "You entered 9" << endl;
    } else if (num == 10) {
        cout << "You entered 10" << endl;
    } else if (num == 11) {
        cout << "You entered 11" << endl;
    } else if (num == 12) {
        cout << "You entered 12" << endl;
    } else if (num == 13) {
        cout << "You entered 13" << endl;
    } else if (num == 14) {
        cout << "You entered 14" << endl;
    } else if (num == 15) {
        cout << "You entered 15" << endl;
    } else if (num == 16) {
        cout << "You entered 16" << endl;
    } else if (num == 17) {
        cout << "You entered 17" << endl;
    } else if (num == 18) {
        cout << "You entered 18" << endl;
    } else if (num == 19) {
        cout << "You entered 19" << endl;
    } else if (num == 20) {
        cout << "You entered 20" << endl;
    } else if (num == 21) {
        cout << "You entered 21" << endl;
    } else if (num == 22) {
        cout << "You entered 22" << endl;
    } else if (num == 23) {
        cout << "You entered 23" << endl;
    } else if (num == 24) {
        cout << "You entered 24" << endl;
    } else if (num == 25) {
        cout << "You entered 25" << endl;
    } else if (num == 26) {
        cout << "You entered 26" << endl;
    } else if (num == 27) {
        cout << "You entered 27" << endl;
    } else if (num == 28) {
        cout << "You entered 28" << endl;
    } else if (num == 29) {
        cout << "You entered 29" << endl;
    } else if (num == 30) {
        cout << "You entered 30" << endl;
    } else if (num == 31) {
        cout << "You entered 31" << endl;
    } else if (num == 32) {
        cout << "You entered 32" << endl;
    } else if (num == 33) {
        cout << "You entered 33" << endl;
    } else if (num == 34) {
        cout << "You entered 34" << endl;
    } else if (num == 35) {
        cout << "You entered 35" << endl;
    } else if (num == 36) {
        cout << "You entered 36" << endl;
    } else if (num == 37) {
        cout << "You entered 37" << endl;
    } else if (num == 38) {
        cout << "You entered 38" << endl;
    } else if (num == 39) {
        cout << "You entered 39" << endl;
    } else if (num == 40) {
        cout << "You entered 40" << endl;
    } else if (num == 41) {
        cout << "You entered 41" << endl;
    } else if (num == 42) {
        cout << "You entered 42" << endl;
    } else if (num == 43) {
        cout << "You entered 43" << endl;
    } else if (num == 44) {
        cout << "You entered 44" << endl;
    } else if (num == 45) {
        cout << "You entered 45" << endl;
    } else if (num == 46) {
        cout << "You entered 46" << endl;
    } else if (num == 47) {
        cout << "You entered 47" << endl;
    } else if (num == 48) {
        cout << "You entered 48" << endl;
    } else if (num == 49) {
        cout << "You entered 49" << endl;
    } else if (num == 50) {
        cout << "You entered 50" << endl;
    } else if (num == 51) {
        cout << "You entered 51" << endl;
    } else if (num == 52) {
        cout << "You entered 52" << endl;
    } else if (num == 53) {
        cout << "You entered 53" << endl;
    } else if (num == 54) {
        cout << "You entered 54" << endl;
    } else if (num == 55) {
        cout << "You entered 55" << endl;
    } else if (num == 56) {
        cout << "You entered 56" << endl;
    } else if (num == 57) {
        cout << "You entered 57" << endl;
    } else if (num == 58) {
        cout << "You entered 58" << endl;
    } else if (num == 59) {
        cout << "You entered 59" << endl;
    } else if (num == 60) {
        cout << "You entered 60" << endl;
    } else if (num == 61) {
        cout << "You entered 61" << endl;
    } else if (num == 62) {
        cout << "You entered 62" << endl;
    } else if (num == 63) {
        cout << "You entered 63" << endl;
    } else if (num == 64) {
        cout << "You entered 64" << endl;
    } else if (num == 65) {
        cout << "You entered 65" << endl;
    } else if (num == 66) {
        cout << "You entered 66" << endl;
    } else if (num == 67) {
        cout << "You entered 67" << endl;
    } else if (num == 68) {
        cout << "You entered 68" << endl;
    } else if (num == 69) {
        cout << "You entered 69" << endl;
    } else if (num == 70) {
        cout << "You entered 70" << endl;
    } else if (num == 71) {
        cout << "You entered 71" << endl;
    } else if (num == 72) {
        cout << "You entered 72" << endl;
    } else if (num == 73) {
        cout << "You entered 73" << endl;
    } else if (num == 74) {
        cout << "You entered 74" << endl;
    } else if (num == 75) {
        cout << "You entered 75" << endl;
    } else if (num == 76) {
        cout << "You entered 76" << endl;
    } else if (num == 77) {
        cout << "You entered 77" << endl;
    } else if (num == 78) {
        cout << "You entered 78" << endl;
    } else if (num == 79) {
        cout << "You entered 79" << endl;
    } else if (num == 80) {
        cout << "You entered 80" << endl;
    } else if (num == 81) {
        cout << "You entered 81" << endl;
    } else if (num == 82) {
        cout << "You entered 82" << endl;
    } else if (num == 83) {
        cout << "You entered 83" << endl;
    } else if (num == 84) {
        cout << "You entered 84" << endl;
    } else if (num == 85) {
        cout << "You entered 85" << endl;
    } else if (num == 86) {
        cout << "You entered 86" << endl;
    } else if (num == 87) {
        cout << "You entered 87" << endl;
    } else if (num == 88) {
        cout << "You entered 88" << endl;
    } else if (num == 89) {
        cout << "You entered 89" << endl;
    } else if (num == 90) {
        cout << "You entered 90" << endl;
    } else if (num == 91) {
        cout << "You entered 91" << endl;
    } else if (num == 92) {
        cout << "You entered 92" << endl;
    } else if (num == 93) {
        cout << "You entered 93" << endl;
    } else if (num == 94) {
        cout << "You entered 94" << endl;
    } else if (num == 95) {
        cout << "You entered 95" << endl;
    } else if (num == 96) {
        cout << "You entered 96" << endl;
    } else if (num == 97) {
        cout << "You entered 97" << endl;
    } else if (num == 98) {
        cout << "You entered 98" << endl;
    } else if (num == 99) {
        cout << "You entered 99" << endl;
    } else if (num == 100) {
        cout << "You entered 100" << endl;
    } else {
        cout << "Invalid input. Please enter a number between 1 and 100." << endl;
    }

    return 0;
}
